/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainRun;

import Drivers.ButtonDriver;
import Drivers.FileDriver;
import LexAnalyzer.Analyzer;
import object.TokenBag;

/**
 *
 * @author aztk
 */
public class AnalyzerGUI extends javax.swing.JFrame {

     /**
      * Creates new form AnalyzerGUI
      */
     Analyzer analyzer;
     TokenBag tokenBag = new TokenBag();
     ButtonDriver buttonDriver = new ButtonDriver();
     FileDriver fileDriver = new FileDriver();

     public AnalyzerGUI() {
          initComponents();
          setLocationRelativeTo(null);
          buttonDriver.initializeTextAreaButtons(textInputArea, undoButton, redoButton, copyButton, pasteButton);
     }

     /**
      * This method is called from within the constructor to initialize the form. WARNING:
      * Do NOT modify this code. The content of this method is always regenerated by the
      * Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          mainPane = new javax.swing.JPanel();
          jScrollPane1 = new javax.swing.JScrollPane();
          textInputArea = new javax.swing.JTextArea();
          analyzerButton = new javax.swing.JButton();
          openFileButton = new javax.swing.JButton();
          saveChangesButton = new javax.swing.JButton();
          saveToButton = new javax.swing.JButton();
          newFileButton = new javax.swing.JButton();
          outputLabel = new javax.swing.JLabel();
          copyButton = new javax.swing.JButton();
          pasteButton = new javax.swing.JButton();
          undoButton = new javax.swing.JButton();
          redoButton = new javax.swing.JButton();
          aboutButton = new javax.swing.JButton();
          jScrollPane3 = new javax.swing.JScrollPane();
          errorsLogsArea = new javax.swing.JTextArea();
          lightModeButton = new javax.swing.JButton();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setTitle("Syntactic Analyzer");
          setBackground(new java.awt.Color(0, 102, 102));
          setPreferredSize(new java.awt.Dimension(1920, 990));
          setResizable(false);

          mainPane.setBackground(new java.awt.Color(0, 102, 102));

          jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
          jScrollPane1.setForeground(new java.awt.Color(102, 102, 102));

          textInputArea.setBackground(new java.awt.Color(102, 102, 102));
          textInputArea.setColumns(20);
          textInputArea.setForeground(new java.awt.Color(255, 255, 255));
          textInputArea.setLineWrap(true);
          textInputArea.setRows(5);
          jScrollPane1.setViewportView(textInputArea);

          analyzerButton.setBackground(new java.awt.Color(102, 0, 51));
          analyzerButton.setForeground(new java.awt.Color(255, 255, 255));
          analyzerButton.setText("Analizar");
          analyzerButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    analyzerButtonActionPerformed(evt);
               }
          });

          openFileButton.setBackground(new java.awt.Color(51, 0, 51));
          openFileButton.setForeground(new java.awt.Color(255, 255, 255));
          openFileButton.setText("Abrir Archivo");
          openFileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
          openFileButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    openFileButtonActionPerformed(evt);
               }
          });

          saveChangesButton.setBackground(new java.awt.Color(51, 0, 51));
          saveChangesButton.setForeground(new java.awt.Color(255, 255, 255));
          saveChangesButton.setText("Guardar");
          saveChangesButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    saveChangesButtonActionPerformed(evt);
               }
          });

          saveToButton.setBackground(new java.awt.Color(51, 0, 51));
          saveToButton.setForeground(new java.awt.Color(255, 255, 255));
          saveToButton.setText("Guardar Como");
          saveToButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    saveToButtonActionPerformed(evt);
               }
          });

          newFileButton.setBackground(new java.awt.Color(51, 0, 51));
          newFileButton.setForeground(new java.awt.Color(255, 255, 255));
          newFileButton.setText("Nuevo");
          newFileButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    newFileButtonActionPerformed(evt);
               }
          });

          outputLabel.setForeground(new java.awt.Color(255, 255, 255));
          outputLabel.setText("Log");

          copyButton.setBackground(new java.awt.Color(51, 0, 51));
          copyButton.setForeground(new java.awt.Color(255, 255, 255));
          copyButton.setText("Copy");

          pasteButton.setBackground(new java.awt.Color(51, 0, 51));
          pasteButton.setForeground(new java.awt.Color(255, 255, 255));
          pasteButton.setText("Paste");

          undoButton.setBackground(new java.awt.Color(51, 0, 51));
          undoButton.setForeground(new java.awt.Color(255, 255, 255));
          undoButton.setText("undo");

          redoButton.setBackground(new java.awt.Color(51, 0, 51));
          redoButton.setForeground(new java.awt.Color(255, 255, 255));
          redoButton.setText("redo");

          aboutButton.setBackground(new java.awt.Color(51, 0, 51));
          aboutButton.setForeground(new java.awt.Color(255, 255, 255));
          aboutButton.setText("Acerca de");
          aboutButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    aboutButtonActionPerformed(evt);
               }
          });

          jScrollPane3.setBackground(new java.awt.Color(102, 102, 102));
          jScrollPane3.setForeground(new java.awt.Color(102, 102, 102));

          errorsLogsArea.setBackground(new java.awt.Color(102, 102, 102));
          errorsLogsArea.setColumns(20);
          errorsLogsArea.setForeground(new java.awt.Color(255, 255, 255));
          errorsLogsArea.setRows(5);
          jScrollPane3.setViewportView(errorsLogsArea);

          lightModeButton.setBackground(new java.awt.Color(0, 8, 27));
          lightModeButton.setForeground(new java.awt.Color(153, 153, 153));
          lightModeButton.setText("☼");
          lightModeButton.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    lightModeButtonActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout mainPaneLayout = new javax.swing.GroupLayout(mainPane);
          mainPane.setLayout(mainPaneLayout);
          mainPaneLayout.setHorizontalGroup(
               mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(mainPaneLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1832, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addGroup(mainPaneLayout.createSequentialGroup()
                              .addGap(2, 2, 2)
                              .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                   .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(mainPaneLayout.createSequentialGroup()
                                             .addComponent(copyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addGap(6, 6, 6)
                                             .addComponent(pasteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(mainPaneLayout.createSequentialGroup()
                                             .addComponent(undoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                             .addGap(6, 6, 6)
                                             .addComponent(redoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(newFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(openFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(analyzerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(saveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(saveToButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(outputLabel))
                                   .addGroup(mainPaneLayout.createSequentialGroup()
                                        .addComponent(lightModeButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(aboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1658, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(97, Short.MAX_VALUE))
          );
          mainPaneLayout.setVerticalGroup(
               mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(mainPaneLayout.createSequentialGroup()
                    .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(mainPaneLayout.createSequentialGroup()
                              .addGap(25, 25, 25)
                              .addComponent(openFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addComponent(analyzerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(saveChangesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(saveToButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(newFileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                              .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(copyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(pasteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(12, 12, 12)
                              .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                   .addComponent(undoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(redoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addGroup(mainPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                   .addComponent(lightModeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                   .addComponent(aboutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                              .addGap(401, 401, 401)
                              .addComponent(outputLabel))
                         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPaneLayout.createSequentialGroup()
                              .addContainerGap()
                              .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(384, Short.MAX_VALUE))
          );

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 60, Short.MAX_VALUE))
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addComponent(mainPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 12, Short.MAX_VALUE))
          );

          pack();
     }// </editor-fold>//GEN-END:initComponents

     private void newFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileButtonActionPerformed

     }//GEN-LAST:event_newFileButtonActionPerformed

     private void saveToButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveToButtonActionPerformed
          fileDriver.saveFile(saveChangesButton, textInputArea);
     }//GEN-LAST:event_saveToButtonActionPerformed

     private void saveChangesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveChangesButtonActionPerformed
          fileDriver.saveFile(saveChangesButton, textInputArea);
     }//GEN-LAST:event_saveChangesButtonActionPerformed

     private void openFileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileButtonActionPerformed
          fileDriver.openFile(openFileButton, textInputArea);
     }//GEN-LAST:event_openFileButtonActionPerformed

     private void analyzerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_analyzerButtonActionPerformed
          analyzer = new Analyzer(textInputArea.getText(), tokenBag);
          errorsLogsArea.setText(tokenBag.showErrors());
     }//GEN-LAST:event_analyzerButtonActionPerformed

     private void lightModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightModeButtonActionPerformed
          buttonDriver.changeLightMode(mainPane, errorsLogsArea, textInputArea, openFileButton, analyzerButton, saveToButton,
                 saveChangesButton, newFileButton, copyButton, pasteButton, undoButton, redoButton, aboutButton, lightModeButton);
     }//GEN-LAST:event_lightModeButtonActionPerformed

     private void aboutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutButtonActionPerformed
          
     }//GEN-LAST:event_aboutButtonActionPerformed

     /**
      * @param args the command line arguments
      */

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton aboutButton;
     private javax.swing.JButton analyzerButton;
     private javax.swing.JButton copyButton;
     private javax.swing.JTextArea errorsLogsArea;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JScrollPane jScrollPane3;
     private javax.swing.JButton lightModeButton;
     private javax.swing.JPanel mainPane;
     private javax.swing.JButton newFileButton;
     private javax.swing.JButton openFileButton;
     private javax.swing.JLabel outputLabel;
     private javax.swing.JButton pasteButton;
     private javax.swing.JButton redoButton;
     private javax.swing.JButton saveChangesButton;
     private javax.swing.JButton saveToButton;
     private javax.swing.JTextArea textInputArea;
     private javax.swing.JButton undoButton;
     // End of variables declaration//GEN-END:variables
}
